# Homework 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [2]:
import numpy as np
import random
a = np.full((4,4),7)
for i in range(4):
    a[i][i] = random.randint(1,4)
a

array([[2, 7, 7, 7],
       [7, 4, 7, 7],
       [7, 7, 2, 7],
       [7, 7, 7, 3]])

2) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [49]:
a = np.array([[i for i in range(4)], [i for i in range(4)], [i for i in range(4)], [i for i in range(4)], [i for i in range(4)]])
a

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

3) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [63]:
a = np.random.randint(0, 10, (10,10))
k = np.zeros(10)
print(a)
for i in range(0,10):
    for j in range(0,10):
        k[i] += a[i,j]
for i in range(0,10):
    k[i] =  k[i]/10
print(k)
for i in range(0,10):
    for j in range(0,10):
        a[i,j] -= k[i]
a

[[3 1 4 9 2 7 2 2 0 1]
 [3 8 3 0 9 3 4 3 6 6]
 [5 2 5 1 8 2 2 3 2 0]
 [8 4 7 9 4 4 0 9 0 7]
 [5 8 2 2 6 6 2 8 9 0]
 [1 8 9 2 1 1 9 1 9 2]
 [7 6 0 7 1 2 3 4 9 5]
 [2 2 8 8 2 3 0 5 9 1]
 [4 0 9 2 6 5 0 3 4 6]
 [3 2 3 7 3 3 3 5 3 2]]
[3.1 4.5 3.  5.2 4.8 4.3 4.4 4.  3.9 3.4]


array([[ 0, -2,  0,  5, -1,  3, -1, -1, -3, -2],
       [-1,  3, -1, -4,  4, -1,  0, -1,  1,  1],
       [ 2, -1,  2, -2,  5, -1, -1,  0, -1, -3],
       [ 2, -1,  1,  3, -1, -1, -5,  3, -5,  1],
       [ 0,  3, -2, -2,  1,  1, -2,  3,  4, -4],
       [-3,  3,  4, -2, -3, -3,  4, -3,  4, -2],
       [ 2,  1, -4,  2, -3, -2, -1,  0,  4,  0],
       [-2, -2,  4,  4, -2, -1, -4,  1,  5, -3],
       [ 0, -3,  5, -1,  2,  1, -3,  0,  0,  2],
       [ 0, -1,  0,  3,  0,  0,  0,  1,  0, -1]])

4) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [65]:
from statistics import median
a = np.random.randint(0, 10, (10,10))
k = np.zeros(10)
print(a)
for i in range(0,10):
        k[i] += median(a[:,i])
        print("median is: ", k[i])
for i in range(0,10):
    for j in range(0,10):
        a[i,j] -= k[i]
a

[[8 1 9 5 9 4 3 7 8 1]
 [8 8 6 7 4 2 4 8 6 5]
 [9 4 7 3 5 1 8 8 1 6]
 [0 8 7 0 7 2 2 9 5 7]
 [6 7 0 2 5 1 1 3 6 0]
 [6 2 6 9 1 3 4 3 9 7]
 [6 2 4 8 9 6 8 8 7 8]
 [9 8 7 8 3 5 5 9 3 5]
 [0 5 5 8 5 8 7 8 2 1]
 [7 6 4 6 7 1 7 0 4 1]]
median is:  6.5
median is:  5.5
median is:  6.0
median is:  6.5
median is:  5.0
median is:  2.5
median is:  4.5
median is:  8.0
median is:  5.5
median is:  5.0


array([[ 1, -5,  2, -1,  2, -2, -3,  0,  1, -5],
       [ 2,  2,  0,  1, -1, -3, -1,  2,  0,  0],
       [ 3, -2,  1, -3, -1, -5,  2,  2, -5,  0],
       [-6,  1,  0, -6,  0, -4, -4,  2, -1,  0],
       [ 1,  2, -5, -3,  0, -4, -4, -2,  1, -5],
       [ 3,  0,  3,  6, -1,  0,  1,  0,  6,  4],
       [ 1, -2,  0,  3,  4,  1,  3,  3,  2,  3],
       [ 1,  0, -1,  0, -5, -3, -3,  1, -5, -3],
       [-5,  0,  0,  2,  0,  2,  1,  2, -3, -4],
       [ 2,  1, -1,  1,  2, -4,  2, -5, -1, -4]])

5) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [40]:
a = np.random.randint(0, 10, (5,5))
#vector_min = np.zeros(5)
#vector_b = np.zeros(5)
vector_min = a.min(axis=1)
vector_max = a.max(axis=1)
a = np.column_stack((a, vector_min))
a = np.column_stack((a, vector_max))
print(a)
print(vector_min)
print(vector_max)
a

[[7 1 6 4 2 1 7]
 [2 6 6 8 8 2 8]
 [4 4 0 1 8 0 8]
 [9 2 0 1 7 0 9]
 [3 4 1 2 9 1 9]]
[1 2 0 0 1]
[7 8 8 9 9]


array([[7, 1, 6, 4, 2, 1, 7],
       [2, 6, 6, 8, 8, 2, 8],
       [4, 4, 0, 1, 8, 0, 8],
       [9, 2, 0, 1, 7, 0, 9],
       [3, 4, 1, 2, 9, 1, 9]])

6) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [91]:
a = np.arange(1, 51)
even = np.array(a[::2])
noteven = np.array(a[a % 2 ==0])
even.shape = (5,5)
noteven.shape = (5,5)
d = (even @ noteven).transpose()
d

array([[ 750, 1850, 2950, 4050, 5150],
       [ 800, 2000, 3200, 4400, 5600],
       [ 850, 2150, 3450, 4750, 6050],
       [ 900, 2300, 3700, 5100, 6500],
       [ 950, 2450, 3950, 5450, 6950]])

7) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [44]:
a = np.zeros((8,8))
for i in range(0,8):
    for j in range(0,8):
        if((i+j) % 2 == 0):
            a[i,j] = 0
        else:
            a[i,j] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])