In [5]:
import numpy as np
import random
class Matrix(object):
    
    def __init__(self, n, m):
        self.n = n
        self.m = m
        self.A = np.zeros((self.n,self.m), dtype=int)
    pass
    def fill_matr(self):
        for i in range(self.n):
            for j in range(self.m):
                self.A[i,j] = random.randint(1,10)
    
    def addit_matr(self,b):
        return self.A + b
    
    def multipl_matr(self,b):
        return self.A @ b

    def multipl_const_matr(self,x):
        return self.A * x

    def det_matr(self):
        return np.linalg.det(self.A)
    
    def inverse_matr(self):
        return np.linalg.inv(self.A)
    
    def transpose_matr(self):
        return self.A.transpose()

a = Matrix(3,3)
a.fill_matr()
b = Matrix(3,3)
b.fill_matr()
b = a.multipl_const_matr(5)
print("Matrix * const: \n",b)
b = a.multipl_matr(b)
print("Matrix * Matrix: \n",b)
b = a.addit_matr(b)
print("Matrix + Matrix: \n",b)
print("Det = ",a.det_matr())
print("Inverse matrix: \n",a.inverse_matr())
print("Transpose matrix: \n",a.transpose_matr())

Matrix * const: 
 [[30  5 50]
 [35 10 25]
 [10 25 45]]
Matrix * Matrix: 
 [[315 290 775]
 [330 180 625]
 [325 285 630]]
Matrix + Matrix: 
 [[321 291 785]
 [337 182 630]
 [327 290 639]]
Det =  215.0000000000001
Inverse matrix: 
 [[-0.03255814  0.19069767 -0.06976744]
 [-0.24651163  0.15813953  0.18604651]
 [ 0.14418605 -0.13023256  0.02325581]]
Transpose matrix: 
 [[ 6  7  2]
 [ 1  2  5]
 [10  5  9]]


In [28]:
def head(pair):
    if pair is None:
        return None
    return pair[0]

def tail(pair, k=1):
    if pair is None:
        return None
    if len(pair) < 2:
        return None
    if(k != 1):
        return tail(pair[1], k-1)
    return pair[1]

def seq(*elements):
    def first(x):
        return x[0]
    def other(x):
        return x[1:]

    if len(elements) == 0:
        return None

    if len(elements) == 1:
        return first(elements), None

    if len(elements) == 2:
        return first(elements), other(elements)

    return first(elements), seq(*other(elements))

def at(pair , i):
    if head(pair) is None:
        return None
    if(i == 0):
        return pair[0]
    #if(pair[i] is None):
    #    return None
    #if(head(pair) == i):
    #    return pair[0]
    #i = i-1
    return at(tail(pair), i - 1)

def size(pair):
    if(pair != None):
        return 1 + size(tail(pair))
    else:
        return 0

def eq(pair1, pair2):
    if(size(pair1) != size(pair2)):
        return False
    if(head(pair1) == head(pair2)):
        if((head(pair1) is None) and (head(pair2) is None)):
            return True
        return eq(tail(pair1), tail(pair2))
    else:
        return False

#def for_each(pair, x):
#    if(pair != None):
#        x = head(pair)
#        return for_each(tail(pair), x)
#    else:
#        return x

def concat(s1, s2):
    def copy(seq):
        if head(seq) is None:
            return
        if tail(seq) is None:
            return seq;
        return head(seq), copy(tail(seq))
    
    def glue(s1, s2):
        if head(s1) is None:
            return
        if tail(s1) is None:
            return s1[0], s2
        return head(s1), glue(tail(s1),s2)
    
    return glue(s1, copy(s2))

def for_each(seq, f):
    if seq is None:
        return
    f(head(seq))
    for_each(tail(seq), f)

def for_each_indexed(seq, f):
    def forEachIndexed(seq, f, index):
        if seq is None:
            return
        f(index, head(seq))
        forEachIndexed(tail(seq), f, index + 1)
    forEachIndexed(seq, f, 0)

s = seq(1,2,3,4,5)
s == (1, (2, (3, (4, (5,)))))
head(s) == 1
tail(s) == (2, (3, (4, (5,))))
print(at(s, 1))
print(eq(concat(seq(1,2), seq(3,4)), seq(1,2,3,4)) == True)
for_each(seq(1,2,3,4), lambda x: print(x,','))
print(for_each_indexed(seq(1,2,3,4), lambda i, x: print(i, x)))

2
True
1 ,
2 ,
3 ,
4 ,
0 1
1 2
2 3
3 4
None
