In [5]:
import numpy as np
import random
class Matrix(object):
    
    def __init__(self, n, m):
        self.n = n
        self.m = m
        self.A = np.zeros((self.n,self.m), dtype=int)
    pass
    def fill_matr(self):
        for i in range(self.n):
            for j in range(self.m):
                self.A[i,j] = random.randint(1,10)
    
    def addit_matr(self,b):
        return self.A + b
    
    def multipl_matr(self,b):
        return self.A @ b

    def multipl_const_matr(self,x):
        return self.A * x

    def det_matr(self):
        return np.linalg.det(self.A)
    
    def inverse_matr(self):
        return np.linalg.inv(self.A)
    
    def transpose_matr(self):
        return self.A.transpose()

a = Matrix(3,3)
a.fill_matr()
b = Matrix(3,3)
b.fill_matr()
b = a.multipl_const_matr(5)
print("Matrix * const: \n",b)
b = a.multipl_matr(b)
print("Matrix * Matrix: \n",b)
b = a.addit_matr(b)
print("Matrix + Matrix: \n",b)
print("Det = ",a.det_matr())
print("Inverse matrix: \n",a.inverse_matr())
print("Transpose matrix: \n",a.transpose_matr())

Matrix * const: 
 [[30  5 50]
 [35 10 25]
 [10 25 45]]
Matrix * Matrix: 
 [[315 290 775]
 [330 180 625]
 [325 285 630]]
Matrix + Matrix: 
 [[321 291 785]
 [337 182 630]
 [327 290 639]]
Det =  215.0000000000001
Inverse matrix: 
 [[-0.03255814  0.19069767 -0.06976744]
 [-0.24651163  0.15813953  0.18604651]
 [ 0.14418605 -0.13023256  0.02325581]]
Transpose matrix: 
 [[ 6  7  2]
 [ 1  2  5]
 [10  5  9]]
