# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [117]:
import numpy as np
numpy.__version__

'1.15.2'

2) Создать нулевой вектор размера 10

In [10]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [14]:
a = np.full(7, 7)
print(a)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [110]:
even = lambda x: x if x % 2 == 0 else False
a = np.array([even(xi) for xi in range(10, 100)])
a = a[::2]
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [85]:
a = np.random.randn(10)
print(a)
a[::-1]

[ 1.76839658  1.14241139 -2.06419742  0.47256051  0.30110297  1.85705463
 -0.72516092 -2.0148082   1.66413236 -0.61531309]


array([-0.61531309,  1.66413236, -2.0148082 , -0.72516092,  1.85705463,
        0.30110297,  0.47256051, -2.06419742,  1.14241139,  1.76839658])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [104]:
a = np.arange(9).reshape((3, 3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [116]:
a = np.eye(4, k=1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])